package datasources

object SCHEMA {
  val VERSION = 0

  // COLLECTIONS
  val cAccessPointsWifi = "accessPointsWifi"
  val cSpaces = "spaces"
  val cCampuses = "campuses"
  val cEdges = "edges"
  val cFingerprintsWifi = "fingerprintsWifi"
  val cFloorplans = "floorplans"
  val cPOIS = "pois"
  val cUsers = "users"

  //// CACHES
  val cFingerprintTime = "cFingerprintTime"
  val cHeatmapWifi1 = "heatmapWifi1"
  val cHeatmapWifi2 = "heatmapWifi2"
  val cHeatmapWifi3 = "heatmapWifi3"
  val cHeatmapWifiTimestamp1 = "heatmapWifiTimestamp1"
  val cHeatmapWifiTimestamp2 = "heatmapWifiTimestamp2"
  val cHeatmapWifiTimestamp3 = "heatmapWifiTimestamp3"

  // FIELDS
  val fAccessToken = "access_token"
  val fAddress = "address"
  val fBuCode = "bucode"
  val fBuid = "buid"
  val fBuids = "buids"
  val fBuidA = "buid_a"
  val fBuidB = "buid_b"
  val fCoOwners = "co_owners"
  val fCoordinates = "coordinates"
  val fCoordinatesLat = "coordinates_lat"
  val fCoordinatesLon = "coordinates_lon"
  val fCampusCuid = "cuid"
  val fConCuid = "cuid"
  val fCount = "count"
  val fDescription = "description"
  val fEdgeType = "edge_type"
  val fEmail = "email"
  val fExternal = "external"
  val fFloor = "floor"
  val fFloorA = "floor_a"
  val fFloorB = "floor_b"
  val fFloorName = "floor_name"
  val fFloorNumber = "floor_number"
  val fFuid = "fuid"
  val fGeometry = "geometry"
  val fGreeklish = "greeklish"
  val fHeading = "heading"
  val fId = "_id"
  val fIsBuildingEntrance = "is_building_entrance"
  val fIsDoor = "is_door"
  val fIsPublished = "is_published"
  val fImage = "image"
  val fLatTopRight = "top_right_lat"
  val fLatBottomLeft = "bottom_left_lat"
  val fLonBottomLeft = "bottom_left_lng"
  val fLonTopRight = "top_right_lng"
  val fLocation = "location"
  val fMac = "MAC"
  val fMeasurements = "measurements"
  val fName = "name"
  val fOwnerId = "owner_id"
  val fUserId = "user_id" // eventually replace owner_id with this
  val fPassword = "password"
  val fPoisA = "pois_a"
  val fPoisB = "pois_b"
  val fPoisType = "pois_type"
  val fPuid = "puid"
  val fRSS = "rss"
  val fSchema = "_schema"
  val fSpaceType = "space_type"
  val fSpaceTypes = Array("building", "vessel")
  val fSum = "sum"
  val fStrongestWifi = "strongestWifi"
  val fTimestamp = "timestamp"
  val fTimestampX = "timestampX"
  val fTimestampY = "timestampY"
  val fType = "type"
  val fURL = "url"
  val fUsername = "username"
  val fWeight = "weight"
  val fX = "x"
  val fY = "y"
  val fZoom = "zoom"
}